name: 'Multiply Values'
description: 'Multiply two values'
inputs:
  secrets:
    description: 'Secrets'
    required: true
  actionInputs:
    description: 'Inputs'
    required: true
outputs:
  product-of-numbers:
    description: "Product of inputs"
    value: ${{ steps.number-multiplication.outputs.result }}
runs:
  using: "composite"
  steps:
    - name: Multiply Two Numbers
      id: number-multiplication
      run: |
         echo "First Number ${FIRST_NUMBER}"
         echo "Second Number: ${SECOND_NUMBER}"
         multiplicationResult=$((FIRST_NUMBER * SECOND_NUMBER))
         echo "result=${multiplicationResult}" >> $GITHUB_OUTPUT
      shell: bash
      env:
        SECRET1: ${{ fromJSON(inputs.secrets).SECRET1 }}
        FIRST_NUMBER: ${{ fromJSON(inputs.actionInputs).first }}
        SECOND_NUMBER: ${{ fromJSON(inputs.actionInputs).second }}



